{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rca-agent.fullname" . }}-mysql
  labels:
    {{- include "rca-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  clusterIP: None
  selector:
    {{- include "rca-agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
{{- end }}
