services:
  mysql:
    image: mysql:8.4
    container_name: rca-agent-mysql

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rca_agent
      MYSQL_USER: rca_agent
      MYSQL_PASSWORD: rca_agent_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-prootpassword"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data: