const API='/api/v1';
let catalog=[];let connections=[];let applications=[];
const qs=(s,r=document)=>r.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,options={}){const r=await fetch(API+path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!r.ok){let d;try{d=await r.json()}catch{}throw new Error(d?.detail||`${r.status} ${r.statusText}`)}return r.status===204?null:r.json()}
function toast(msg){const e=qs('#toast');e.textContent=msg;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),3500)}
function provider(type){return catalog.find(x=>x.provider_type===type)}
function fieldValue(input,field){if(field.type==='boolean')return input.checked;if(field.type==='number')return input.value===''?null:Number(input.value);if(field.type==='json'){if(!input.value.trim())return {};return JSON.parse(input.value)}return input.value}
function fieldsHtml(fields=[],values={},prefix='f'){return fields.map(f=>{const v=values?.[f.name]??f.default??'';if(f.type==='boolean')return `<label class="switch"><input data-field="${esc(f.name)}" id="${prefix}-${esc(f.name)}" type="checkbox" ${v?'checked':''}> ${esc(f.label)}</label>`;if(f.type==='select')return `<label>${esc(f.label)}<select data-field="${esc(f.name)}" id="${prefix}-${esc(f.name)}">${(f.options||[]).map(o=>`<option ${String(v)===String(o)?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;if(f.type==='json')return `<label class="full">${esc(f.label)}<textarea data-field="${esc(f.name)}" id="${prefix}-${esc(f.name)}">${esc(JSON.stringify(v||{},null,2))}</textarea></label>`;return `<label>${esc(f.label)}<input data-field="${esc(f.name)}" id="${prefix}-${esc(f.name)}" type="${f.type==='password'?'password':f.type==='number'?'number':'text'}" value="${esc(v)}" placeholder="${esc(f.placeholder||'')}"></label>`}).join('')}
function collectFields(root,fields=[]){const out={};for(const f of fields){const el=root.querySelector(`[data-field="${f.name}"]`);if(!el)continue;const v=fieldValue(el,f);if(v!==null&&v!==''&&!(typeof v==='object'&&Object.keys(v).length===0))out[f.name]=v}return out}

async function refresh(){[catalog,connections,applications]=await Promise.all([api('/provider-catalog').then(x=>x.items),api('/connections').then(x=>x.items),api('/applications').then(x=>x.items)]);renderConnections();renderApplications()}

function resetViewDetailState(viewName){
  if(viewName==='applications' && typeof closeApplicationDetail==='function') closeApplicationDetail();
  if(viewName==='connections' && typeof closeConnectionDetail==='function') closeConnectionDetail();
  if(viewName==='investigations'){
    qs('#investigation-detail')?.classList.add('hidden');
    qs('#investigation-editor')?.classList.add('hidden');
    qs('#investigations-list')?.classList.remove('hidden');
    qs('#investigations-view .section-head')?.classList.remove('hidden');
  }
}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{
  resetViewDetailState(b.dataset.view);
  document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));
  document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));
  qs(`#${b.dataset.view}-view`).classList.remove('hidden');
});
qs('[data-view="applications"]')?.classList.add('active');
qs('#new-connection').onclick=()=>openConnectionEditor();qs('#new-application').onclick=()=>openApplicationEditor();

function renderConnections(){const root=qs('#connections-list');root.innerHTML=connections.map(c=>{const p=provider(c.provider_type);return `<div class="card"><h3>${esc(c.name)}</h3><div class="meta">${esc(p?.label||c.provider_type)} · ${c.enabled?'enabled':'disabled'}</div><p>${esc(c.config?.base_url||c.config?.context||'Runtime connection')}</p><span class="badge ${c.has_credentials?'ok':''}">${c.has_credentials?'credentials saved':'no credentials'}</span><div class="actions"><button onclick="openConnectionEditor(${c.id})">Edit</button>${['prometheus','elasticsearch'].includes(c.provider_type)?`<button onclick="testConnection(${c.id})">Test</button>`:''}<button class="danger" onclick="deleteConnection(${c.id})">Delete</button></div></div>`}).join('')||'<p>No connections configured yet.</p>'}
function openConnectionEditor(id=null){const item=connections.find(x=>x.id===id);const root=qs('#connection-editor');root.classList.remove('hidden');const type=item?.provider_type||catalog.find(x=>x.implemented)?.provider_type||'prometheus';root.innerHTML=`<h2>${item?'Edit':'New'} connection</h2><div class="grid"><label>Name<input id="conn-name" value="${esc(item?.name||'')}"></label><label>Provider<select id="conn-provider" ${item?'disabled':''}>${catalog.map(p=>`<option value="${esc(p.provider_type)}" ${p.provider_type===type?'selected':''}>${esc(p.label)}${p.implemented?'':' (planned)'}</option>`).join('')}</select></label><label class="switch"><input id="conn-enabled" type="checkbox" ${item?.enabled===false?'':'checked'}> Enabled</label></div><div id="conn-provider-fields" class="grid subpanel"></div><div id="conn-secrets" class="grid subpanel"></div><div class="actions"><button class="primary" id="save-conn">Save</button><button id="cancel-conn">Cancel</button></div>`;
 const render=()=>{const p=provider(qs('#conn-provider').value);qs('#conn-provider-fields').innerHTML=`<div class="full"><h3>Connection settings</h3><p class="hint">Stored in MySQL connections.config.</p></div>${fieldsHtml(p?.connection_fields,item?.config||{},'conn')}`;qs('#conn-secrets').innerHTML=`<div class="full"><h3>Credentials</h3><p class="hint">Credentials are encrypted using RCA_MASTER_KEY. Existing secrets are never returned to the browser.</p></div>${fieldsHtml(p?.credential_fields,{},'secret')}`};render();qs('#conn-provider').onchange=render;qs('#cancel-conn').onclick=()=>root.classList.add('hidden');qs('#save-conn').onclick=async()=>{try{const p=provider(qs('#conn-provider').value);const payload={name:qs('#conn-name').value.trim(),provider_type:qs('#conn-provider').value,config:collectFields(qs('#conn-provider-fields'),p?.connection_fields),enabled:qs('#conn-enabled').checked};let saved;if(item)saved=await api(`/connections/${item.id}`,{method:'PATCH',body:JSON.stringify({name:payload.name,config:payload.config,enabled:payload.enabled})});else saved=await api('/connections',{method:'POST',body:JSON.stringify(payload)});const secrets=collectFields(qs('#conn-secrets'),p?.credential_fields);if(Object.keys(secrets).length)await api(`/connections/${saved.id}/credentials`,{method:'PUT',body:JSON.stringify({credentials:secrets})});toast('Connection saved in MySQL');await refresh();if(typeof closeConnectionDetail==='function')closeConnectionDetail();else root.classList.add('hidden')}catch(e){toast(e.message)}};root.scrollIntoView({behavior:'smooth'})}
async function testConnection(id){try{const r=await api(`/connections/${id}/test`,{method:'POST'});toast(r.message||`Connection ${r.status||'ok'}`)}catch(e){toast(`Test failed: ${e.message}`)}}
async function deleteConnection(id){if(!confirm('Delete this connection? Existing tool bindings may reference it.'))return;try{await api(`/connections/${id}`,{method:'DELETE'});toast('Connection deleted');await refresh()}catch(e){toast(e.message)}}

function renderApplications(){const root=qs('#applications-list');root.innerHTML=applications.map(a=>`<div class="card"><h3>${esc(a.name)}</h3><div class="meta">${esc(a.slug)} · ${esc(a.investigation_strategy)}</div><p>${esc(a.description||'')}</p><span class="badge ${a.enabled?'ok':'warn'}">${a.enabled?'enabled':'disabled'}</span><div class="actions"><button onclick="openApplicationEditor(${a.id})">Configure</button><button class="danger" onclick="deleteApplication(${a.id})">Delete</button></div></div>`).join('')||'<p>No applications configured yet.</p>'}
async function openApplicationEditor(id=null){const item=id?await api(`/applications/${id}`):null;const root=qs('#application-editor');root.classList.remove('hidden');root.innerHTML=`<h2>${item?'Configure application':'New application'}</h2><div class="grid"><label>Name<input id="app-name" value="${esc(item?.name||'')}"></label><label>Slug<input id="app-slug" value="${esc(item?.slug||'')}"></label><label>Investigation strategy<select id="app-strategy"><option value="agentic" ${item?.investigation_strategy==='agentic'?'selected':''}>agentic</option><option value="collect_then_analyze" ${item?.investigation_strategy==='collect_then_analyze'?'selected':''}>collect_then_analyze</option></select></label><label class="switch"><input id="app-enabled" type="checkbox" ${item?.enabled===false?'':'checked'}> Enabled</label><label class="full">Description<textarea id="app-description">${esc(item?.description||'')}</textarea></label></div><div class="actions"><button class="primary" id="save-app">Save application</button><button id="cancel-app">Cancel</button></div>${item?`<div class="subpanel"><h2>Application tools</h2><div id="app-tools"></div><button id="add-tool">Add tool</button></div><div class="subpanel"><h2>Dependencies</h2><div id="dependencies"></div><button id="add-dependency">Add dependency</button></div>`:''}`;
 qs('#cancel-app').onclick=()=>root.classList.add('hidden');qs('#save-app').onclick=async()=>{try{const payload={name:qs('#app-name').value.trim(),slug:qs('#app-slug').value.trim(),description:qs('#app-description').value.trim()||null,enabled:qs('#app-enabled').checked,investigation_strategy:qs('#app-strategy').value};let saved;if(item)saved=await api(`/applications/${item.id}`,{method:'PATCH',body:JSON.stringify(payload)});else saved=await api('/applications',{method:'POST',body:JSON.stringify(payload)});toast('Application saved in MySQL');await refresh();if(!item)openApplicationEditor(saved.id)}catch(e){toast(e.message)}};
 if(item){renderTools(item);renderDependencies(item);qs('#add-tool').onclick=()=>toolForm(item);qs('#add-dependency').onclick=()=>dependencyForm(item)}root.scrollIntoView({behavior:'smooth'})}
function renderTools(app){const r=qs('#app-tools');r.innerHTML=(app.tools||[]).map(t=>`<div class="tool-row"><div class="row"><strong>${esc(t.tool_type)}</strong><span class="badge">${esc(t.provider_type)}</span><span class="meta">priority ${t.priority}</span></div><pre>${esc(JSON.stringify(t.config||{},null,2))}</pre><div class="actions"><button onclick="editTool(${app.id},${t.id})">Edit</button><button class="danger" onclick="deleteTool(${app.id},${t.id})">Delete</button></div></div>`).join('')||'<p>No tools bound to this application.</p>'}
function toolForm(app,existing=null){const r=qs('#app-tools');const wrap=document.createElement('div');wrap.className='tool-row';const initial=existing?.provider_type||'prometheus';wrap.innerHTML=`<div class="grid"><label>Provider<select class="tool-provider">${catalog.map(p=>`<option value="${esc(p.provider_type)}" ${p.provider_type===initial?'selected':''}>${esc(p.label)}${p.implemented?'':' (planned)'}</option>`).join('')}</select></label><label>Tool type<select class="tool-type"></select></label><label>Connection<select class="tool-connection"></select></label><label>Priority<input class="tool-priority" type="number" value="${existing?.priority??100}"></label><label class="switch"><input class="tool-enabled" type="checkbox" ${existing?.enabled===false?'':'checked'}> Enabled</label></div><div class="tool-fields grid"></div><div class="actions"><button class="primary tool-save">Save tool</button><button class="tool-cancel">Cancel</button></div>`;r.appendChild(wrap);
 const render=()=>{const p=provider(qs('.tool-provider',wrap).value);qs('.tool-type',wrap).innerHTML=(p?.tool_types||[]).map(t=>`<option ${t===existing?.tool_type?'selected':''}>${esc(t)}</option>`).join('');const matches=connections.filter(c=>c.provider_type===p?.provider_type);qs('.tool-connection',wrap).innerHTML=`<option value="">None/runtime</option>`+matches.map(c=>`<option value="${c.id}" ${c.id===existing?.connection_id?'selected':''}>${esc(c.name)}</option>`).join('');qs('.tool-fields',wrap).innerHTML=`<div class="full"><h3>Tool settings</h3><p class="hint">Stored in MySQL application_tools.config.</p></div>${fieldsHtml(p?.tool_fields,existing?.config||{},'tool')}`};render();qs('.tool-provider',wrap).onchange=render;qs('.tool-cancel',wrap).onclick=()=>wrap.remove();qs('.tool-save',wrap).onclick=async()=>{try{const p=provider(qs('.tool-provider',wrap).value);const payload={tool_type:qs('.tool-type',wrap).value,provider_type:p.provider_type,connection_id:qs('.tool-connection',wrap).value?Number(qs('.tool-connection',wrap).value):null,config:collectFields(qs('.tool-fields',wrap),p.tool_fields),enabled:qs('.tool-enabled',wrap).checked,priority:Number(qs('.tool-priority',wrap).value||100)};if(existing)await api(`/application-tools/${existing.id}`,{method:'PATCH',body:JSON.stringify(payload)});else await api(`/applications/${app.id}/tools`,{method:'POST',body:JSON.stringify(payload)});toast('Tool settings saved in MySQL');openApplicationEditor(app.id)}catch(e){toast(e.message)}}}
async function editTool(appId,toolId){const app=await api(`/applications/${appId}`);const t=app.tools.find(x=>x.id===toolId);toolForm(app,t)}
async function deleteTool(appId,toolId){if(!confirm('Delete this tool binding?'))return;await api(`/application-tools/${toolId}`,{method:'DELETE'});toast('Tool deleted');openApplicationEditor(appId)}

async function renderDependencies(app){const r=qs('#dependencies');const blocks=[];for(const d of app.dependencies||[]){const tools=await api(`/dependencies/${d.id}/tools`).then(x=>x.items);blocks.push(`<div class="dep-row"><div class="row"><strong>${esc(d.name)}</strong><span class="badge">${esc(d.dependency_type)}</span></div><p>${esc(d.description||'')}</p>${tools.map(t=>`<div class="tool-row"><strong>${esc(t.tool_type)}</strong> · ${esc(t.provider_type)}<pre>${esc(JSON.stringify(t.config||{},null,2))}</pre><button class="danger" onclick="deleteDependencyTool(${app.id},${t.id})">Delete tool</button></div>`).join('')}<div class="actions"><button onclick="dependencyToolForm(${app.id},${d.id})">Add diagnostic tool</button><button class="danger" onclick="deleteDependency(${app.id},${d.id})">Delete dependency</button></div></div>`)}r.innerHTML=blocks.join('')||'<p>No dependencies configured.</p>'}
function dependencyForm(app){const r=qs('#dependencies');const w=document.createElement('div');w.className='dep-row';w.innerHTML=`<div class="grid"><label>Name<input class="dep-name"></label><label>Type<input class="dep-type" placeholder="redis, rabbitmq, database, external"></label><label class="full">Description<textarea class="dep-description"></textarea></label></div><div class="actions"><button class="primary dep-save">Save dependency</button><button class="dep-cancel">Cancel</button></div>`;r.appendChild(w);qs('.dep-cancel',w).onclick=()=>w.remove();qs('.dep-save',w).onclick=async()=>{try{await api(`/applications/${app.id}/dependencies`,{method:'POST',body:JSON.stringify({name:qs('.dep-name',w).value.trim(),dependency_type:qs('.dep-type',w).value.trim(),description:qs('.dep-description',w).value.trim()||null,enabled:true})});toast('Dependency saved');openApplicationEditor(app.id)}catch(e){toast(e.message)}}}
async function dependencyToolForm(appId,depId){const app=await api(`/applications/${appId}`);const r=qs('#dependencies');const w=document.createElement('div');w.className='tool-row';w.innerHTML=`<h3>Dependency diagnostic tool</h3><div class="grid"><label>Provider<select class="dt-provider">${catalog.map(p=>`<option value="${esc(p.provider_type)}">${esc(p.label)}</option>`).join('')}</select></label><label>Tool type<select class="dt-type"></select></label><label>Connection<select class="dt-connection"></select></label></div><div class="dt-fields grid"></div><div class="actions"><button class="primary dt-save">Save</button><button class="dt-cancel">Cancel</button></div>`;r.prepend(w);const render=()=>{const p=provider(qs('.dt-provider',w).value);qs('.dt-type',w).innerHTML=(p?.tool_types||[]).map(x=>`<option>${esc(x)}</option>`).join('');qs('.dt-connection',w).innerHTML='<option value="">None</option>'+connections.filter(c=>c.provider_type===p?.provider_type).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');qs('.dt-fields',w).innerHTML=fieldsHtml(p?.tool_fields,{},'dt')};render();qs('.dt-provider',w).onchange=render;qs('.dt-cancel',w).onclick=()=>w.remove();qs('.dt-save',w).onclick=async()=>{try{const p=provider(qs('.dt-provider',w).value);await api(`/dependencies/${depId}/tools`,{method:'POST',body:JSON.stringify({tool_type:qs('.dt-type',w).value,provider_type:p.provider_type,connection_id:qs('.dt-connection',w).value?Number(qs('.dt-connection',w).value):null,config:collectFields(qs('.dt-fields',w),p.tool_fields),enabled:true})});toast('Dependency tool saved');openApplicationEditor(appId)}catch(e){toast(e.message)}}}
async function deleteDependency(appId,id){if(!confirm('Delete dependency and its diagnostic bindings?'))return;await api(`/dependencies/${id}`,{method:'DELETE'});toast('Dependency deleted');openApplicationEditor(appId)}
async function deleteDependencyTool(appId,id){await api(`/dependency-tools/${id}`,{method:'DELETE'});toast('Dependency tool deleted');openApplicationEditor(appId)}
async function deleteApplication(id){if(!confirm('Delete application configuration? Historical investigations are preserved.'))return;await api(`/applications/${id}`,{method:'DELETE'});toast('Application deleted');await refresh()}

