"""link investigations to alerts

Revision ID: aa9846a88aa0
Revises: 5283b1eaa642
Create Date: 2026-09-13 12:19:42.270499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9846a88aa0'
down_revision: Union[str, Sequence[str], None] = '5283b1eaa642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('alert_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_investigations_alert_id'), 'investigations', ['alert_id'], unique=False)
    op.create_foreign_key(None, 'investigations', 'alerts', ['alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.drop_index(op.f('ix_investigations_alert_id'), table_name='investigations')
    op.drop_column('investigations', 'alert_id')
    # ### end Alembic commands ###
